http:
  port: 8080
admin:
  port: 9876
  host: localhost
apiEndpoints:
  api:
    host: localhost
    paths: '/ip'
  todo:
    host: localhost
    paths: ['/todo', '/todo/*']  
serviceEndpoints:
  httpbin:
    url: 'https://httpbin.org'
  todoService:
    url: 'http://localhost:3000'  
policies:
  - basic-auth
  - cors
  - expression
  - key-auth
  - log
  - oauth2
  - proxy
  - rate-limit
pipelines:
  default:
    apiEndpoints:
      - api
    policies:
    # Uncomment `key-auth:` when instructed to in the Getting Started guide.
    # - key-auth:
      - proxy:
          - action:
              serviceEndpoint: httpbin 
              changeOrigin: true
  todoPipeline: 
    apiEndpoints:
      - todo
    policies:  
     # Uncomment `key-auth:` when instructed to in the Getting Started guide.
    # - key-auth
       - proxy:
          - action:
              serviceEndpoint: todoService
              changeOrigin: true